package com.konkuk.boost.persistence

import android.provider.BaseColumns

object AppContract {
    object AppEntry: BaseColumns {
        const val USERNAME = "username"
        const val YEAR = "year"
        const val SEMESTER = "semester"
        const val RANK = "rank"
        const val TOTAL = "total"
        const val TYPE = "type"
        const val SUBJECT_AREA_NAME = "subjectAreaName"
        const val EVALUATION_METHOD = "evaluationMethod"
        const val CLASSIFICATION = "classification"
        const val CHARACTER_GRADE = "characterGrade"
        const val GRADE = "grade"
        const val PROFESSOR = "professor"
        const val SUBJECT_ID = "subjectId"
        const val SUBJECT_NUMBER = "subjectNumber"
        const val SUBJECT_NAME = "subjectName"
        const val SUBJECT_POINT = "subjectPoint"
        const val SUBJECT_AREA = "subjectArea"
        const val KEY = "key"
        const val VALUE = "value"
        const val BEFORE_DEPT = "beforeDept"
        const val BEFORE_SUST = "beforeSust"
        const val BEFORE_MAJOR = "beforeMajor"
        const val CHANGED_CODE = "changedCode"
        const val CHANGED_DATE = "changedDate"
        const val CHANGED_YEAR = "changedYear"
        const val CHANGED_SEMESTER = "changedSemester"
        const val DEPT = "dept"
        const val SUST = "sust"
        const val MAJOR = "major"
        const val SCHOLARSHIP_NAME = "scholarshipName"
        const val SCHOLARSHIP_ENTER_AMOUNT = "scholarshipEnterAmount"
        const val SCHOLARSHIP_TUITION_AMOUNT = "scholarshipTuitionAmount"
        const val ETC_AMOUNT = "etcAmount"
        const val SCHOLARSHIP_DATE = "date"
        const val STANDARD = "standard"
        const val ACQUIRED = "acquired"
        const val REMAINDER = "remainder"
        const val MODIFIED_AT = "modified_at"
        const val APPLY_DATE = "applyDate"
        const val CHANGED_REASON = "changedReason"
        const val APPLIED_STATE_CODE = "appliedStateCode"
        const val PAID_DATE = "paidDate"
        const val TUITION_AMOUNT = "tuitionAmount"
        const val ENTER_AMOUNT = "enterAmount"
        const val STATE_CODE = "stateCode"
        const val PRIMARY_KEYS = "primaryKeys"
    }

}