name: CI workflow

on:
  push:
    branches: [ main ]

jobs:
  apk:
    name: Generate APK
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v1

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      
      - name: Install gpg
        run: sudo apt-get install gnupg
      
      - name: Load secrets
        run: 
          gpg --quiet --batch --yes --always-trust --decrypt="services.tar.gpg" --passphrase="$FIREBASE_SECRET" --output services.tar services.tar.gpg
          tar xvf services.tar
        env: 
          FIREBASE_SECRET: ${{ secrets.FIREBASE_SECRET }}

      - name: Build debug APK
        run: bash ./gradlew assembleDebug --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: app
          path: app/build/outputs/apk/debug/app-debug.apk
